'use client';

import {
    AlertCircle,
    ArrowRight,
    BarChart3,
    Calendar,
    Car,
    CheckCircle,
    ChevronDown,
    ChevronFirst,
    ChevronLast,
    ClipboardList,
    CreditCard,
    DollarSign,
    Download,
    Edit,
    Eye,
    FileText,
    Filter,
    HelpCircle,
    Home,
    LayoutDashboard,
    Loader2,
    LogOut,
    Menu,
    Moon,
    MoreHorizontal,
    Package,
    PieChart,
    Plus,
    RefreshCw,
    Search,
    Settings,
    Sheet,
    Shield,
    SlidersHorizontal,
    Star,
    Sun,
    Trash,
    TrendingUp,
    Upload,
    User,
    Users,
    Wallet,
    X,
    HandCoins,
    Truck,
    ChartNoAxesCombined,
} from 'lucide-react';

export const Icons = {
    // Nav Icons
    dashboard: LayoutDashboard,
    calendar: Calendar,
    car: Car,
    truck: Truck,
    users: Users,
    profile: User,
    hand: HandCoins,
    package: Package,
    wallet: Wallet,
    finance: DollarSign,
    chart: BarChart3,
    pieChart: PieChart,
    trending: TrendingUp,
    clipboardList: ClipboardList,
    fileText: FileText,
    creditCard: CreditCard,
    shield: Shield,
    settings: Settings,
    home: Home,
    chartCombined: ChartNoAxesCombined,

    // Action Icons
    arrowRight: ArrowRight,
    plus: Plus,
    edit: Edit,
    trash: Trash,
    eye: Eye,
    download: Download,
    upload: Upload,
    filter: Filter,
    search: Search,
    refresh: RefreshCw,
    sliders: SlidersHorizontal,
    moreHorizontal: MoreHorizontal,
    x: X,
    menu: Menu,
    chvDown: ChevronDown,
    chevFirst: ChevronFirst,
    chevLast: ChevronLast,

    // Status Icons
    alertCircle: AlertCircle,
    checkCircle: CheckCircle,
    helpCircle: HelpCircle,
    star: Star,
    sheet: Sheet,

    // Theme Icons
    sun: Sun,
    moon: Moon,

    // Auth Icons
    logOut: LogOut,

    // Utility Icons
    loader: Loader2,
};
